/*
# Create Contact Submissions Table
This migration creates a new table to store submissions from the website's contact form.

## Query Description: 
This is a non-destructive operation that adds a new table. It does not affect any existing data.

## Metadata:
- Schema-Category: "Structural"
- Impact-Level: "Low"
- Requires-Backup: false
- Reversible: true (can be dropped)

## Structure Details:
- Table: public.contact_submissions
  - Columns:
    - id: bigint (primary key, auto-incrementing)
    - created_at: timestamptz (defaults to now())
    - name: text
    - email: text
    - phone: text
    - company: text
    - service: text
    - message: text

## Security Implications:
- RLS Status: Enabled
- Policy Changes: Yes, a new policy is added to allow public inserts.
- Auth Requirements: None for insertion (public table).

## Performance Impact:
- Indexes: Primary key on 'id'.
- Triggers: None
- Estimated Impact: Low, as it's a new table for write-only operations from the frontend.
*/

CREATE TABLE public.contact_submissions (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    name text,
    email text,
    phone text,
    company text,
    service text,
    message text
);

-- Enable Row Level Security
ALTER TABLE public.contact_submissions ENABLE ROW LEVEL SECURITY;

-- Allow public insert access for the contact form
CREATE POLICY "Allow public insert" ON public.contact_submissions FOR INSERT WITH CHECK (true);
